apiVersion: v1
kind: Service
metadata:
  name: chatgpt-ui
  namespace: chatgpt-ui
spec:
  selector:
    app: chatgpt-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
