apiVersion: v1
kind: Service
metadata:
  name: chatgpt-ui
  namespace: chatgpt-ui
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: chatgpt-ui
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
